name: "SRNE Monitor"
description: "Monitor SRNE Solar Inverter Combo values"
url: https://github.com/jgimbel/srne-solar-inverter-mqtt
version: "1.0"
slug: "srnemonitor"
init: false
host_dbus: true
apparmor: false

homeassistant_api: true # http://supervisor/core/api
hassio_api: true        # http://supervisor

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

services:
  - mqtt:need

discovery:
  - mqtt

homeassistant_api: true
host_network: true
uart: true
usb: true
gpio: true
audio: true
apparmor: false
host_dbus: true
docker_api: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN
  - SYS_RAWIO
  - SYS_TIME
  - SYS_NICE
devices:
  - /dev/ttyUSB*
  - /dev/serial/**


options:
  device: /dev/ttyUSB0
  device_id: 1
  sample_period: 1.0

schema:
  device: str
  device_id: "int(1,65535)"

  mqtt_user: "str?"
  mqtt_password: "str?"
  mqtt_broker: "str?"
  mqtt_port: "int(1,65535)?"

  sample_period: "float"